LAST_ADD_CRF=True
USELSTM=True
CRF_LEARNING_RATE = 1e-2
LSTM_LEARNING_RATE = 3e-5
LSTM_HIDDEN_SIZE = 512
USE_LOSSGATE = False
ATTENTION_LEARNING_RATE = 3e-5
DROPOUT=0.1

MUSE_HEAD=5
MUSE_MASK=False
from jointBERT_biModle_attention8 import JointBERTCRFLSTM