LAST_ADD_CRF=True
USELSTM=True
CRF_LEARNING_RATE = 1e-2
LSTM_LEARNING_RATE = 1e-3
ATTENTION_LEARNING_RATE =2e-2
LSTM_HIDDEN_SIZE = 512
USE_LOSSGATE = False
DROPOUT=0.1

MUSE_HEAD=2
MUSE_MASK=False
ATTENTION_MASK=False
from convlab2.nlu.jbca5.diachat.jointBERT_biModle_attention5 import JointBERTCRFLSTM