LAST_ADD_CRF=True
USELSTM=True
CRF_LEARNING_RATE = 1e-2
LSTM_LEARNING_RATE = 1e-3
LSTM_HIDDEN_SIZE = 512
USE_LOSSGATE = False
DROPOUT=0.1
DROPOUTINTENT=0.2
from intentatte2_cnn import JointBERTCRFLSTM